### ISSUE TITLE
The timescale container is always restarting

### ISSUE THREAD

**Issue by Artlands** [dell/iDRAC-Telemetry-Reference-Tools#14] opened 2021-12-07 01:39 UTC
I was trying to use the tool with the timescale pipeline. However, the timescale container is always restarting:

```
$ docker-compose -f ./timescale-docker-pipeline-reference-unenc.yml up -d
Starting activemq  ... done
Starting timescale          ... done
Starting grafana            ... done
Starting mysqldb            ... done
Starting timescale-ingester ... done
Starting telemetry-receiver ... done
$ docker-compose -f ./timescale-docker-pipeline-reference-unenc.yml ps
       Name                     Command                 State             Ports
--------------------------------------------------------------------------------------
activemq             /bin/bash -c bin/activemq  ...   Up           61616/tcp, 8161/tcp
grafana              /run.sh                          Up           3000/tcp
mysqldb              docker-entrypoint.sh mysqld      Up           3306/tcp, 33060/tcp
telemetry-receiver   /bin/sh -c cmd/idrac-telem ...   Up
timescale            /bin/sh -c cmd/initialize_ ...   Restarting
timescale-ingester   go run cmd/timescalepump/t ...   Up
```

Its docker logs are like this: 

```
$ docker logs --tail 50 --follow --timestamps timescale
2021-12-07T01:27:26.172757282Z 	Is the server running locally and accepting
2021-12-07T01:27:26.172759726Z 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2021-12-07T01:27:27.092481235Z psql: error: could not connect to server: No such file or directory
```

**Comment by SailM23** [comment] 2022-01-13 17:36
Hello Artlands, This issue is fixed with the latest change. Could you verify with the latest code and mark this issue fixed? Do you see the timescale container restarting on a VM or independent physical machine?

**Comment by cjmadathil** [comment] 2022-01-14 15:59
Closing the issue based on the fix provided. Please contact us/re-open this issue if the problem is still observed.

**Closed by cjmadathil** 2022-01-14 15:59 UTC
